/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/renderer/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface':                  '#111317',
        'surface-dim':              '#111317',
        'surface-bright':           '#37393e',
        'surface-container-lowest': '#0c0e12',
        'surface-container-low':    '#1a1c20',
        'surface-container':        '#1e2024',
        'surface-container-high':   '#282a2e',
        'surface-container-highest':'#333539',
        'surface-variant':          '#333539',
        'on-surface':               '#e2e2e8',
        'on-surface-variant':       '#c2c6d6',
        'inverse-surface':          '#e2e2e8',
        'inverse-on-surface':       '#2f3035',
        'outline':                  '#8c909f',
        'outline-variant':          '#424754',
        'primary':                  '#adc6ff',
        'primary-container':        '#4d8eff',
        'on-primary':               '#002e6a',
        'on-primary-container':     '#00285d',
        'primary-fixed':            '#d8e2ff',
        'primary-fixed-dim':        '#adc6ff',
        'secondary':                '#ffb3ad',
        'secondary-container':      '#a40217',
        'on-secondary':             '#68000a',
        'on-secondary-container':   '#ffaea8',
        'tertiary':                 '#4ae176',
        'tertiary-container':       '#00a74b',
        'on-tertiary':              '#003915',
        'on-tertiary-fixed':        '#002109',
        'on-tertiary-container':    '#003111',
        'error':                    '#ffb4ab',
        'error-container':          '#93000a',
        'on-error':                 '#690005',
        'on-error-container':       '#ffdad6',
        'background':               '#111317',
        'on-background':            '#e2e2e8',
      },
      fontFamily: {
        sans:          ['Inter', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        // Labels/chips/badges/buttons/timecodes use Inter (with `tabular-nums` where
        // numbers must align). The `mono` token name is retained for the many
        // `font-mono` usages, but maps to Inter — not a monospace face.
        mono:          ['Inter', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        // Named type-scale aliases matching the Stitch design system
        'label-sm':    ['Inter', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        'timecode-lg': ['Inter', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        'headline-md': ['Inter', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
        'display-lg':  ['Inter', '-apple-system', 'BlinkMacSystemFont', 'sans-serif'],
      },
      fontSize: {
        'label-sm':    ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' }],
        'body-md':     ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'display-lg':  ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        sm:      '0.125rem',
        md:      '0.25rem',
        lg:      '0.25rem',
        xl:      '0.5rem',
        '2xl':   '0.75rem',
        full:    '9999px',
      },
      spacing: {
        xs:             '4px',
        sm:             '8px',
        md:             '16px',
        lg:             '24px',
        xl:             '32px',
        gutter:         '12px',
        'panel-margin': '16px',
      },
    },
  },
  plugins: [],
};
