import { contextBridge, ipcRenderer } from 'electron';
import { BUNDLED_FONTS, DEFAULT_FONT } from './fonts.js';

contextBridge.exposeInMainWorld('cue', {
  songs: {
    search: (query) => ipcRenderer.invoke('songs:search', query),
    get: (id) => ipcRenderer.invoke('songs:get', id),
    listAll: () => ipcRenderer.invoke('songs:listAll'),
    create: (data) => ipcRenderer.invoke('songs:create', data),
    update: (id, data) => ipcRenderer.invoke('songs:update', id, data),
    delete: (id) => ipcRenderer.invoke('songs:delete', id),
    addTag: (songId, tagId) => ipcRenderer.invoke('songs:addTag', songId, tagId),
    removeTag: (songId, tagId) => ipcRenderer.invoke('songs:removeTag', songId, tagId),
    setBackground: (songId, mediaId) => ipcRenderer.invoke('songs:setBackground', songId, mediaId),
    setLock: (songId, locked) => ipcRenderer.invoke('songs:setLock', songId, locked),
    deleteAll: () => ipcRenderer.invoke('songs:deleteAll'),
    importParse: (filePaths) => ipcRenderer.invoke('songs:importParse', filePaths),
    importGhs: () => ipcRenderer.invoke('songs:importGhs'),
    importCommit: (parsedSongs) => ipcRenderer.invoke('songs:importCommit', parsedSongs),
    matchTitles: (rawText) => ipcRenderer.invoke('songs:matchTitles', rawText),
    scrapeSearch: (query) => ipcRenderer.invoke('songScrape:search', query),
    scrapeFetch: (candidate) => ipcRenderer.invoke('songScrape:fetch', candidate),
    applyStyleToSong: (songId, styleJson) => ipcRenderer.invoke('songs:applyStyleToSong', songId, styleJson),
    // CCLI usage reporting
    logUsage: (songId) => ipcRenderer.invoke('songs:logUsage', songId),
    usageReport: (fromIso, toIso) => ipcRenderer.invoke('songs:usageReport', fromIso, toIso),
    usageClear: () => ipcRenderer.invoke('songs:usageClear'),
  },
  tags: {
    list: () => ipcRenderer.invoke('tags:list'),
    create: (data) => ipcRenderer.invoke('tags:create', data),
    update: (id, data) => ipcRenderer.invoke('tags:update', id, data),
    delete: (id) => ipcRenderer.invoke('tags:delete', id),
  },
  services: {
    list: () => ipcRenderer.invoke('services:list'),
    get: (id) => ipcRenderer.invoke('services:get', id),
    create: (data) => ipcRenderer.invoke('services:create', data),
    update: (id, data) => ipcRenderer.invoke('services:update', id, data),
    delete: (id) => ipcRenderer.invoke('services:delete', id),
    reorderItems: (serviceId, orderedIds) => ipcRenderer.invoke('services:reorderItems', serviceId, orderedIds),
    addItem: (serviceId, item) => ipcRenderer.invoke('services:addItem', serviceId, item),
    addItems: (serviceId, items) => ipcRenderer.invoke('services:addItems', serviceId, items),
    removeItem: (itemId) => ipcRenderer.invoke('services:removeItem', itemId),
    setItemBackground: (itemId, mediaId) => ipcRenderer.invoke('services:setItemBackground', itemId, mediaId),
    setItemLoop:  (itemId, loop)  => ipcRenderer.invoke('services:setItemLoop',  itemId, loop),
    setItemAdvance: (itemId, seconds, loop, wrap) => ipcRenderer.invoke('services:setItemAdvance', itemId, seconds, loop, wrap),
    duplicateItem: (itemId) => ipcRenderer.invoke('services:duplicateItem', itemId),
    applyBackgroundToRundown: (serviceId, mediaId) => ipcRenderer.invoke('services:applyBackgroundToRundown', serviceId, mediaId),
    clearItems: (serviceId) => ipcRenderer.invoke('services:clearItems', serviceId),
    exportPdf: (serviceId) => ipcRenderer.invoke('services:exportPdf', serviceId),
  },
  output: {
    go: (payload) => ipcRenderer.invoke('output:go', payload),
    clear: () => ipcRenderer.invoke('output:clear'),
    logo: () => ipcRenderer.invoke('output:logo'),
    logoInfo: (channelId) => ipcRenderer.invoke('output:logo-info', channelId),
    setLive: (enabled) => ipcRenderer.invoke('output:setLive', enabled),
    getState: () => ipcRenderer.invoke('output:getState'),
    media: {
      control: (action) => ipcRenderer.invoke('output:media:control', action),
      seek: (pos) => ipcRenderer.invoke('output:media:seek', pos),
      setMuted: (muted) => ipcRenderer.invoke('output:media:set-muted', muted),
      setLoop: (loop) => ipcRenderer.invoke('output:media:set-loop', loop),
      setRate: (rate) => ipcRenderer.invoke('output:media:set-rate', rate),
    },
    audioDevice: {
      get: () => ipcRenderer.invoke('output:audio-device:get'),
      set: (device) => ipcRenderer.invoke('output:audio-device:set', device),
    },
    stream: {
      start: () => ipcRenderer.invoke('output:stream:start'),
      stop: () => ipcRenderer.invoke('output:stream:stop'),
      status: () => ipcRenderer.invoke('output:stream:status'),
      getConfig: () => ipcRenderer.invoke('output:stream:config:get'),
      setConfig: (cfg) => ipcRenderer.invoke('output:stream:config:set', cfg),
      // Stream studio: external feed inputs + layout/cut. open/close are ref-counted
      // by the Stream tab and keep the compositor window alive for live preview.
      getStudio: () => ipcRenderer.invoke('output:stream:studio:get'),
      setStudio: (cfg) => ipcRenderer.invoke('output:stream:studio:set', cfg),
      open: () => ipcRenderer.invoke('output:stream:studio:open'),
      close: () => ipcRenderer.invoke('output:stream:studio:close'),
      // Saveable layout presets (free-form feed/program composition).
      getPresets: () => ipcRenderer.invoke('output:stream:presets:get'),
      savePreset: (p) => ipcRenderer.invoke('output:stream:presets:save', p),
      deletePreset: (id) => ipcRenderer.invoke('output:stream:presets:delete', id),
    },
    channels: {
      list: () => ipcRenderer.invoke('output:channels:list'),
      create: (data) => ipcRenderer.invoke('output:channels:create', data),
      update: (id, data) => ipcRenderer.invoke('output:channels:update', id, data),
      delete: (id) => ipcRenderer.invoke('output:channels:delete', id),
    },
    monitors: {
      list: (channelId) => ipcRenderer.invoke('output:monitors:list', channelId),
      create: (channelId, data) => ipcRenderer.invoke('output:monitors:create', channelId, data),
      delete: (monitorId) => ipcRenderer.invoke('output:monitors:delete', monitorId),
    },
    multiview: {
      start: () => ipcRenderer.invoke('output:multiview:start'),
      stop: () => ipcRenderer.invoke('output:multiview:stop'),
    },
    stage: {
      message:    (text)           => ipcRenderer.invoke('output:stage:message', text),
      timer:      (action, seconds) => ipcRenderer.invoke('output:stage:timer', action, seconds),
      getTimer:   ()               => ipcRenderer.invoke('output:stage:timer:get'),
      getMessage: ()               => ipcRenderer.invoke('output:stage:message:get'),
      getSchedule: ()              => ipcRenderer.invoke('output:stage:schedule:get'),
      schedule:    (msg)        => ipcRenderer.invoke('output:stage:schedule:add', msg),
      unschedule:  (id)         => ipcRenderer.invoke('output:stage:schedule:remove', id),
      // Customisable WYSIWYG layout (per channel) + reusable named presets.
      getLayout:    (channelId)         => ipcRenderer.invoke('output:stage:layout:get', channelId),
      setLayout:    (channelId, layout) => ipcRenderer.invoke('output:stage:layout:set', channelId, layout),
      getPresets:   ()         => ipcRenderer.invoke('output:stage:preset:list'),
      savePreset:   (preset)   => ipcRenderer.invoke('output:stage:preset:save', preset),
      deletePreset: (id)       => ipcRenderer.invoke('output:stage:preset:delete', id),
    },
    lowerthird: {
      setFontScale: (pct) => ipcRenderer.invoke('output:lowerthird:set-font-scale', pct),
    },
    graphic: {
      show: (data) => ipcRenderer.invoke('output:graphic:show', data),
      hide: (target) => ipcRenderer.invoke('output:graphic:hide', target),
      showCustom: (data) => ipcRenderer.invoke('output:custom:show', data),
      hideCustom: (target) => ipcRenderer.invoke('output:custom:hide', target),
    },
    ticker: {
      show: (data) => ipcRenderer.invoke('output:ticker:show', data),
      hide: (target) => ipcRenderer.invoke('output:ticker:hide', target),
    },
    countdown: {
      show: (data) => ipcRenderer.invoke('output:countdown:show', data),
      hide: (target) => ipcRenderer.invoke('output:countdown:hide', target),
      pause: (target) => ipcRenderer.invoke('output:countdown:pause', target),
      resume: (target) => ipcRenderer.invoke('output:countdown:resume', target),
    },
    overlay: {
      get: () => ipcRenderer.invoke('output:overlay:get'),
    },
    screens: {
      list: () => ipcRenderer.invoke('output:screens:list'),
    },
  },
  graphics: {
    list: () => ipcRenderer.invoke('graphics:list'),
    get: (id) => ipcRenderer.invoke('graphics:get', id),
    create: (data) => ipcRenderer.invoke('graphics:create', data),
    update: (id, data) => ipcRenderer.invoke('graphics:update', id, data),
    delete: (id) => ipcRenderer.invoke('graphics:delete', id),
    reorder: (orderedIds) => ipcRenderer.invoke('graphics:reorder', orderedIds),
    presets: () => ipcRenderer.invoke('graphics:presets'),
  },
  scenes: {
    list:    ()            => ipcRenderer.invoke('scenes:list'),
    get:     (id)          => ipcRenderer.invoke('scenes:get', id),
    create:  (data)        => ipcRenderer.invoke('scenes:create', data),
    update:  (id, data)    => ipcRenderer.invoke('scenes:update', id, data),
    delete:  (id)          => ipcRenderer.invoke('scenes:delete', id),
    reorder: (orderedIds)  => ipcRenderer.invoke('scenes:reorder', orderedIds),
    apply:   (scene)       => ipcRenderer.invoke('scenes:apply', scene),
  },
  // Output Presets — save & recall the output rig (channels/displays/NDI/stream/stage).
  // Separate from scenes; apply is orchestrated in the renderer (OutputPresetsPanel).
  outputPresets: {
    list:    ()           => ipcRenderer.invoke('outputPresets:list'),
    get:     (id)         => ipcRenderer.invoke('outputPresets:get', id),
    create:  (data)       => ipcRenderer.invoke('outputPresets:create', data),
    update:  (id, data)   => ipcRenderer.invoke('outputPresets:update', id, data),
    delete:  (id)         => ipcRenderer.invoke('outputPresets:delete', id),
    reorder: (orderedIds) => ipcRenderer.invoke('outputPresets:reorder', orderedIds),
  },
  // Live video inputs (NDI receive) — network sources routed to the program.
  liveInput: {
    sources: (waitMs) => ipcRenderer.invoke('liveInput:sources', waitMs),
    available: () => ipcRenderer.invoke('liveInput:available'),
    getEnabled: () => ipcRenderer.invoke('liveInput:getEnabled'),
    setEnabled: (v) => ipcRenderer.invoke('liveInput:setEnabled', v),
    previewStart: (sourceName) => ipcRenderer.invoke('liveInput:previewStart', sourceName),
    previewStop: (sourceName) => ipcRenderer.invoke('liveInput:previewStop', sourceName),
  },
  media: {
    import: (filePaths) => ipcRenderer.invoke('media:import', filePaths),
    get: (id) => ipcRenderer.invoke('media:get', id),
    list: (folderId) => ipcRenderer.invoke('media:list', folderId),
    listAll: () => ipcRenderer.invoke('media:listAll'),
    delete: (id) => ipcRenderer.invoke('media:delete', id),
    deleteMany: (ids) => ipcRenderer.invoke('media:deleteMany', ids),
    deleteAll: () => ipcRenderer.invoke('media:deleteAll'),
    findUnused: () => ipcRenderer.invoke('media:findUnused'),
    getDiskUsage: () => ipcRenderer.invoke('media:getDiskUsage'),
    getMediaDir: () => ipcRenderer.invoke('media:getMediaDir'),
    folders: {
      create: (name, parentId) => ipcRenderer.invoke('media:folders:create', name, parentId),
      rename: (id, name) => ipcRenderer.invoke('media:folders:rename', id, name),
      delete: (id) => ipcRenderer.invoke('media:folders:delete', id),
      tree: () => ipcRenderer.invoke('media:folders:tree'),
    },
  },
  backgrounds: {
    list: () => ipcRenderer.invoke('backgrounds:list'),
    tagCounts: () => ipcRenderer.invoke('backgrounds:tagCounts'),
    download: (id) => ipcRenderer.invoke('backgrounds:download', id),
    applyAsDefault: (id, surface, toAll) => ipcRenderer.invoke('backgrounds:applyAsDefault', id, surface, toAll),
  },
  bible: {
    versions: () => ipcRenderer.invoke('bible:versions:list'),
    importFile: (filePath, meta) => ipcRenderer.invoke('bible:importFile', filePath, meta),
    onlineList: () => ipcRenderer.invoke('bible:online:list'),
    onlineDownload: (abbrev) => ipcRenderer.invoke('bible:online:download', abbrev),
    delete: (id) => ipcRenderer.invoke('bible:delete', id),
    books: (versionId) => ipcRenderer.invoke('bible:books', versionId),
    chapters: (versionId, bookNum) => ipcRenderer.invoke('bible:chapters', versionId, bookNum),
    verses: (versionId, bookNum, chapter) => ipcRenderer.invoke('bible:verses', versionId, bookNum, chapter),
    adjacent: (versionId, bookNum, chapter, verse, dir) => ipcRenderer.invoke('bible:adjacent', versionId, bookNum, chapter, verse, dir),
    resolve: (versionId, ref, versesPerSlide) => ipcRenderer.invoke('bible:resolve', versionId, ref, versesPerSlide),
    search: (versionId, query) => ipcRenderer.invoke('bible:search', versionId, query),
  },
  themes: {
    list:           ()                       => ipcRenderer.invoke('themes:list'),
    get:            (id)                     => ipcRenderer.invoke('themes:get', id),
    create:         (data)                   => ipcRenderer.invoke('themes:create', data),
    update:         (id, data)               => ipcRenderer.invoke('themes:update', id, data),
    delete:         (id)                     => ipcRenderer.invoke('themes:delete', id),
    applyToSong:       (themeId, songId, setBg) => ipcRenderer.invoke('themes:applyToSong', themeId, songId, setBg),
    applyToRundown:    (themeId, svcId, setBg)  => ipcRenderer.invoke('themes:applyToRundown', themeId, svcId, setBg),
    applyToAllSongs:   (themeId, setBg)         => ipcRenderer.invoke('themes:applyToAllSongs', themeId, setBg),
    resolveBackground: (themeId)                => ipcRenderer.invoke('themes:resolveBackground', themeId),
  },
  presentations: {
    list:          ()              => ipcRenderer.invoke('presentations:list'),
    get:           (id)            => ipcRenderer.invoke('presentations:get', id),
    create:        (data)          => ipcRenderer.invoke('presentations:create', data),
    update:        (id, data)      => ipcRenderer.invoke('presentations:update', id, data),
    delete:        (id)            => ipcRenderer.invoke('presentations:delete', id),
    reorderSlides: (id, orderedIds)=> ipcRenderer.invoke('presentations:reorderSlides', id, orderedIds),
    templates: {
      list:   ()      => ipcRenderer.invoke('presentationTemplates:list'),
      get:    (id)    => ipcRenderer.invoke('presentationTemplates:get', id),
      create: (data)  => ipcRenderer.invoke('presentationTemplates:create', data),
      delete: (id)    => ipcRenderer.invoke('presentationTemplates:delete', id),
    },
    detectLibreOffice:  ()          => ipcRenderer.invoke('presentations:detectLibreOffice'),
    setLibreOfficePath: (p)         => ipcRenderer.invoke('presentations:setLibreOfficePath', p),
    convertPptx:        (filePath)  => ipcRenderer.invoke('presentations:convertPptx', filePath),
    createFromImages:   (title, buffers) => ipcRenderer.invoke('presentations:createFromImages', title, buffers),
    sermonGenerate:     (payload)   => ipcRenderer.invoke('sermon:generate', payload),
  },
  youtube: {
    prefetch: (url) => ipcRenderer.invoke('youtube:prefetch', url),
    readClipboard: () => ipcRenderer.invoke('clipboard:readText'),
    status:   (url) => ipcRenderer.invoke('youtube:status', url),
    cancel:   (url) => ipcRenderer.invoke('youtube:cancel', url),
    detect:   ()    => ipcRenderer.invoke('youtube:detect'),
  },
  scriptureDetect: {
    getConfig:       () => ipcRenderer.invoke('scriptureDetect:getConfig'),
    setConfig:       (patch) => ipcRenderer.invoke('scriptureDetect:setConfig', patch),
    start:           (engine) => ipcRenderer.invoke('scriptureDetect:start', engine),
    stop:            () => ipcRenderer.invoke('scriptureDetect:stop'),
    ensureAsrModel:  () => ipcRenderer.invoke('scriptureDetect:ensureAsrModel'),
    buildVectors:    (versionId) => ipcRenderer.invoke('scriptureDetect:buildVectors', versionId),
    getGpuModelUsage:() => ipcRenderer.invoke('scriptureDetect:getGpuModelUsage'),
    // High-rate PCM frames — fire-and-forget send (no reply); transfer the buffer.
    pushAudio:       (int16) => ipcRenderer.send('scriptureDetect:pushAudio', int16.buffer),
    // Utterance text from the WebGPU worker (CPU path uses pushAudio instead).
    ingestTranscript:(payload) => ipcRenderer.send('scriptureDetect:ingestTranscript', payload),
  },
  openExternal: (url) => ipcRenderer.invoke('app:openExternal', url),
  packages: {
    list:     ()   => ipcRenderer.invoke('packages:list'),
    install:  (id) => ipcRenderer.invoke('packages:install', id),
    remove:   (id) => ipcRenderer.invoke('packages:remove', id),
    reveal:   (id) => ipcRenderer.invoke('packages:reveal', id),
    locate:   (id) => ipcRenderer.invoke('packages:locate', id),
  },
  remote: {
    getConfig:       () => ipcRenderer.invoke('remote:getConfig'),
    setConfig:       (data) => ipcRenderer.invoke('remote:setConfig', data),
    regenerateToken: () => ipcRenderer.invoke('remote:regenerateToken'),
    regenerateViewToken: () => ipcRenderer.invoke('remote:regenerateViewToken'),
    pushNavState:    (s) => ipcRenderer.invoke('remote:navState', s),
  },
  settings: {
    get: (key) => ipcRenderer.invoke('settings:get', key),
    set: (key, value) => ipcRenderer.invoke('settings:set', key, value),
    setGlobalLogo: (mediaId) => ipcRenderer.invoke('settings:setGlobalLogo', mediaId),
    setGlobalBackground: (type, mediaId) => ipcRenderer.invoke('settings:setGlobalBackground', type, mediaId),
    applyBackgroundToAll: (type, mediaId) => ipcRenderer.invoke('settings:applyBackgroundToAll', type, mediaId),
    getDiskUsage: () => ipcRenderer.invoke('settings:getDiskUsage'),
    getDataPath: () => ipcRenderer.invoke('settings:getDataPath'),
    openDataFolder: () => ipcRenderer.invoke('settings:openDataFolder'),
    exportBackup: () => ipcRenderer.invoke('settings:exportBackup'),
    importBackup: () => ipcRenderer.invoke('settings:importBackup'),
    factoryReset: () => ipcRenderer.invoke('settings:factoryReset'),
    checkForUpdate: () => ipcRenderer.invoke('settings:checkForUpdate'),
    downloadUpdate: (asset) => ipcRenderer.invoke('settings:downloadUpdate', asset),
  },
  dialog: {
    openFile: (options) => ipcRenderer.invoke('dialog:openFile', options),
  },
  fonts: {
    list: BUNDLED_FONTS,
    default: DEFAULT_FONT,
    listUser: () => ipcRenderer.invoke('fonts:listUser'),
    css: () => ipcRenderer.invoke('fonts:css'),
    import: () => ipcRenderer.invoke('fonts:import'),
    delete: (id) => ipcRenderer.invoke('fonts:delete', id),
  },
  platform: process.platform,
  window: {
    minimize: () => ipcRenderer.invoke('window:minimize'),
    maximize: () => ipcRenderer.invoke('window:maximize'),
    close:    () => ipcRenderer.invoke('window:close'),
  },
  on: (channel, callback) => {
    const allowed = [
      'output:unresolved-channels', 'output:state-changed',
      'output:ndi-unavailable', 'output:ndi-sender-error', 'output:ndi-sender-ok',
      'output:multiview-captures',
      'output:media-transport',
      'output:overlay-changed',
      'stage:schedule', 'stage:layout', 'stage:timer', 'stage:message',
      'shortcut:next', 'shortcut:prev',
      'remote:command',
      'youtube:status',
      'scripture:detected', 'scripture:transcript', 'scripture:status',
      'update:progress', 'update:available',
      'packages:progress',
      'stream:status', 'output:stream-preview', 'output:stream-levels',
      'liveinput:preview', 'liveinput:status', 'liveinput:enabled',
    ];
    if (!allowed.includes(channel)) return () => {};
    const wrapper = (_event, ...args) => callback(...args);
    ipcRenderer.on(channel, wrapper);
    return () => ipcRenderer.removeListener(channel, wrapper);
  },
  off: (channel, callback) => {
    ipcRenderer.removeListener(channel, callback);
  },
});
